version: '3.1'

services:

  spigot:
    build:
      context: .
      args:
        spigot_ver: 1.14.3
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
      - ./push:/push_src
    env_file:
      - spigot.env
      - secret.env
    environment:
      SPIGOT_MEM: 4G
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: spigot_plugins
    depends_on:
      - db

  db:
    image: mariadb
    env_file: secret.env
    environment:
      MYSQL_DATABASE: spigot_plugins
    volumes:
      - mysql:/var/lib/mysql
    command:
      - --wait_timeout=10800

volumes:
  mysql:
    driver: local
